### ISSUE TITLE
将默认分支由master修改为main

### ISSUE THREAD

**Issue by TCOTC** [leolee9086/SACDownloadManager#1]
点击 README 里的「[中文](https://github.com/leolee9086/SACDownloadManager/blob/main/README_zh_CN.md)」直接 404 了

**Comment by leolee9086** [comment]
啊啊啊  改漏了改漏了, 晚点更正

**Comment by leolee9086** [comment]
https://github.com/leolee9086/SACDownloadManager/commit/9af1e030e48756f2b062daaa34debb7dcfaacef1

已经处理，感谢
