### ISSUE TITLE
希望不仅仅是子文档，孙文档也可以下载

### ISSUE THREAD

**Issue by Chenm4** [leolee9086/SACDownloadManager#2]
下载的只能是子文档，孙文档下载不了，希望能加上

**Comment by leolee9086** [comment]
https://github.com/leolee9086/SACDownloadManager/commit/9af1e030e48756f2b062daaa34debb7dcfaacef1 

已经增加递归下载功能，感谢反馈，更新插件之后注意需要刷新思源的界面

参考：
https://ld246.com/article/1709633448368
